# Site settings
title: Andreas Wagner
description: 'www.awagner.net'
url: 'http://awagner.net'
#url: 'http://localhost:4000'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Andreas Wagner'
  email: a.wagner@tum.de
  github_username: #AndreasAWagner
  linkedin_username: AndreasAWagner
  xing_username: AndreasAWagner
  google-scholar_username: YVUNungAAAAJ

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
include: ['_pages']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
